server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Any route that doesn't have a file extension (e.g. /devices)
    # will be routed to index.html to let React Router handle it.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
